config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :pets do
    resources :services, only: :create
  end

  resources :services, except: %i[new show create]
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :users, through: :services

  has_one_attached :photo
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :pet
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pets
  has_many :services
  has_many :pets, through: :services

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:petwalker])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys:
                                      %i[photo name address region city description price_per_hour phone_number])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :set_petwalkers, only: :home

  def home
    redirect_to services_path if user_signed_in? && current_user.petwalker
  end

  private

  def set_petwalkers
    @petwalkers = User.where(petwalker: true)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[show edit update destroy]

  def index
    @pets = Pet.all
  end

  def show
    @pets = Pet.all
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user

    if @pet.save
      redirect_to @pet, notice: 'Pet was successfully created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update

    if @pet.update(pet_params)
      redirect_to @pet, notice: 'Pet was successfully updated!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path, notice: 'Pet was successfully destroyed.'
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :breed, :important_note, :photo)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_pet, only: %i[new create]
  before_action :set_petwalkers, only: :edit
  before_action :set_service, only: %i[edit update destroy]
  before_action :set_services, only: :index
  before_action :set_state, only: :update

  def index
    set_services
  end

  def create
    @service = Service.new(service_params)
    @service.pet = @pet
    @service.state = 'scheduled'

    if @service.save
      redirect_to services_path, notice: 'Service was successfully created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @service.state.nil?
      @service.state = 'scheduled'
      if @service.update(service_params)
        redirect_to services_path, notice: 'Service was successfully updated!'
      else
        render :new, status: :unprocessable_entity
      end
    else
      if @service.update(params.permit(:data))
        redirect_to services_path, notice: 'Service was successfully updated!'
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @service.destroy
    redirect_to services_path, notice: 'Service was successfully destroyed!'
  end

  private

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end

  def set_petwalkers
    set_service
    @petwalkers = User.where(petwalker: true).where.not(id: @service.user)
  end

  def set_state
    @service.state = params['state']
    @service.started_at = Time.now if @service.state == 'in process'
    @service.finished_at = Time.now if @service.state == 'completed'

    if @service.state == 'completed'
      @service.price = (((@service.finished_at - @service.started_at) / 3600) * @service.user.price_per_hour).round
    end
  end

  def set_service
    @service = Service.find(params[:id])
  end

  def set_services
    if current_user.petwalker
      @services = Service.where(user: current_user)
    else
      @services = Service.where(pet: Pet.where(user: current_user))
    end
  end

  def service_params
    params.require(:service).permit(:pet_id, :user_id, :schedule, :state, :price,
                                    :started_at, :finished_at, :rating, :review)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super

    unless current_user.petwalker
      pet = Pet.new
      pet.user = current_user
      pet.name = 'My pet'
      pet.save
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_pet, only: :show
  before_action :set_petwalker, only: :show
  before_action :set_petwalkers, only: :show
  before_action :set_reviews, only: :show
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @service = Service.new
  end

  private

  def set_pet
    @pet = Pet.where(user: current_user).first
  end

  def set_petwalker
    @petwalker = User.find(params[:id])
  end

  def set_petwalkers
    @petwalkers = [User.find(@petwalker.id)]
  end

  def set_reviews
    set_petwalker
    services = Service.where(user_id: @petwalker)
    @reviews = services.map { |service| { message: service.review, rating: service.rating } }
    # @petwalker_rating =
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WalkingPetApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
  <!--Dogs Walkers-->
  <div class="container">
    <div class="row justify-content-center">
      <% @petwalkers.each do |petwalker| %>
        <div class="col-lg-3 mb-3 mx-2 border border-primary">
          <div class="box">
              <% if petwalker.photo.attached? %>
                <%= cl_image_tag petwalker.photo.key, class: 'card-img-top', style: "border-radius: 5%", width: 70 %>
              <% else %>
                <!--<i class="fa-solid fa-paw card-img-top"></i>-->
                  <%= image_tag "petwalker.png", style: "border-radius: 5%", class: "card-img-top"%>
              <% end %>

              <h5 class="card-title m-3"></h5>
              <%= petwalker.name %>
              <p class="card-description"><%= "#{petwalker.price_per_hour}/hour" %></p>
              <%= link_to 'RESERV', user_path(petwalker), class: 'mb-3 btn btn-primary' %>
          </div>
        </div>
        <% end %>
    </div>
  </div>

  <!--Footer-->
  <div class="footer text-white bg-primary">
    <p>The walking pet team</p>
  </div>

app/views/pets/_form.html.erb
<section class="get_in_touch">
  <h1 class="title">Ingresa una nueva mascota</h1>
  <div class="container">

    <%= simple_form_for @pet do |f| %>
      <div class="form-inputs contact-form row">

      <div class="form-field col-lg-12">
        <%= f.label :foto, class: 'photo' %>
        <%= f.input :photo, as: :file, label: false, class: 'input-text' %>
      </div>


      <div class="form-field col-lg-6">
        <%= f.text_field :name, label: false, class: 'input-text', placeholder: ' ' %>
        <%= f.label :name, class: 'label' %>
      </div>

      <div class="form-field col-lg-6">
        <%= f.text_field :breed, label: false, class: 'input-text', placeholder: ' ' %>
        <%= f.label :breed, class: 'label' %>
      </div>

      <div class="form-field col-lg-12">
        <%= f.text_field :important_note, label: false, class: 'input-text', placeholder: ' ' %>
        <%= f.label :important_note, class: 'label' %>
      </div>


      </div>

      <div class="form-actions d-flex justify-content-between">
        <%= f.button :submit, class: "btn btn-primary submit-btn" %>
        <div class="d-flex">
          <p>Ya tienes una mascota?</p>
          <%= link_to "Lista de mascotas", pets_path, class: "btn btn-primary mx-1" %>
        </div>
      </div>
    <% end %>
   </div>
</section>

app/views/pets/edit.html.erb
<%= render 'form', pet: @pet %>

<div>
  <%= link_to "Back to pets", pets_path %>
</div>

app/views/pets/index.html.erb
<div class="row row-cols-3 mx-auto py-2">
  <% @pets.each do |pet| %>
    <div class="col">
      <div class="card text-center p-3 pb-md-4 mx-auto" style="width: 18rem;">
        <% if pet.photo.attached? %>
          <%= cl_image_tag pet.photo.key, class: 'card-img-top' %>
        <% else %>
          <!--<i class="fa-solid fa-paw card-img-top"></i>-->
          <p>
          <%= image_tag "puppy.png", size: "auto", style: "border-radius: 20%", class: "card-img-top"%>
          </p>
        <% end %>
        <div class="card-body">
          <%= link_to "#{pet.name} 👈", pet_path(pet), class: 'card-title' %>
          <h3><%= pet.breed %></h3>
          <h4><%= pet.important_note %></h4>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class = "d-grid gap-2 col-6 mx-auto">
<%= link_to 'New pet', new_pet_path, class: 'btn btn-primary' %>
</div>

app/views/pets/new.html.erb
<div class="div">
<%= render 'form' %>
</div>

app/views/pets/show.html.erb
<br>

<h1> Your pets 🐾</h1>

<div class="row row-cols-3 mx-auto py-2">
  <% @pets.each do |pet| %>
    <div class="col">
      <div class="card text-left p-3 pb-md-4 mx-auto" style="width: 18rem;">
        <% if pet.photo.attached? %>
          <%= cl_image_tag pet.photo.key, class: "card-img-top" %>
        <% else %>
          <%= image_tag "puppy.png", size: "auto", style: "border-radius: 5%", class: "card-img-top"%>
        <% end %>

        <div class="card-body">
          <h4 class="card-title"><%= @pet.name %></h4>
          <h6 class="card-subtitle"><%= @pet.breed %></h6>
          <br>
          <p class="card-text"><%= @pet.important_note %></p>
          <br>
          <div class="row row-cols-1">

          <%= link_to 'Edit pet', edit_pet_path(@pet), class: 'btn btn-sm btn-info col' %>
          <%= link_to 'New service', new_pet_service_path(@pet), class: 'btn btn-sm btn-danger col' %>
          </div>
          <div class="col align-self-end"><%= link_to 'Delete pet', pet_path(@pet), method: :delete, class: "btn btn-sm btn-warning col" %></div>

        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'Back', pets_path, class: 'btn btn-info' %>

app/views/services/_form.html.erb
<section class="get_in_touch">
  <div class="container">
    <%= simple_form_for [@pet, @service] do |f| %>
      <div class="form-inputs contact-form">

        <div class="form-field col-lg-12">
          <%= f.label :Paseador, class: 'label-service' %>
          <%= f.association :user, collection: @petwalkers, label: false, class: 'input-text', label_method: :email %>
        </div>

        <div class="form-field col-lg-12">
          <%= f.label :Fecha, class: 'label-service' %>
          <%= f.input :schedule, label: false, class: 'input-text', required: true %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-primary" %>
        </div>

      </div>
    <% end %>

    <%= link_to "Back to services", services_path, class: "btn btn-primary" %>
  </div>
</section>

app/views/services/_service.html.erb
<% if current_user.petwalker %>

  <div class="container">
  <div class="row">
      <div class="col-lg-12">
          <div class="card card-margin">
              <div class="card-header no-border">
                  <h5 class="card-title"><i class="fa-solid fa-paw card-img-top"></i></h5>
              </div>
              <div class="card-body pt-0">
                  <div class="widget-49">
                      <div class="widget-49-title-wrapper">
                          <div class="widget-49-date-primary">
                              <span class="widget-49-date-day">7</span>
                              <span class="widget-49-date-month">apr</span>
                          </div>
                          <div class="widget-49-meeting-info">
                              <span class="widget-49-pro-title">Servicio de Paseo</span>
                              <span class="widget-49-meeting-time">Status: <%= service.state %> </span>
                          </div>
                      </div>
                      <ol class="widget-49-meeting-points">
                          <li class="widget-49-meeting-item"><span>Paseador: <%= service.user.name %></span></li>
                          <li class="widget-49-meeting-item"><span>Dueño de la mascota: <%= service.pet.user.name %></span></li>
                          <% if service.state == 'completed' %>
                            <li class="widget-49-meeting-item"><span>Price: <%= service.price %></span></li>
                          <% end %>
                      </ol>
                      <div class="widget-49-meeting-action">

                        <div class="d-flex justify-content-between">
                        <% if service.state == 'scheduled' %>
                          <%= button_to 'Accept', service_path(service), method: :patch, params: { state: 'accepted' }, class: "btn btn-info mb-3"  %>

                          <%= button_to 'Deny', service_path(service), method: :patch, params: { state: 'denied' }, class: "btn btn-info"  %>
                        <% end %>
                        </div>


                        <% if service.state == 'accepted' %>
                          <%= button_to 'Start', service_path(service), method: :patch, params: { state: 'started' }, class: "btn btn-info"  %>
                        <% end %>

                        <% if service.state == 'in process' %>
                          <%= button_to 'Finalize', service_path(service), method: :patch, params: { state: 'finished' }, class: "btn btn-info"  %>
                        <% end %>



                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  </div>



<% else %>


    <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="card card-margin">
                <div class="card-header no-border">
                    <h5 class="card-title"><i class="fa-solid fa-paw card-img-top"></i></h5>
                </div>
                <div class="card-body pt-0">
                    <div class="widget-49">
                        <div class="widget-49-title-wrapper">
                            <div class="widget-49-date-primary">
                                <span class="widget-49-date-day">7</span>
                                <span class="widget-49-date-month">apr</span>
                            </div>
                            <div class="widget-49-meeting-info">
                                <span class="widget-49-pro-title">Servicio de Paseo</span>
                                <span class="widget-49-meeting-time">Status: <%= service.state %> </span>
                            </div>
                        </div>
                        <ol class="widget-49-meeting-points">
                            <li class="widget-49-meeting-item"><span>Paseador: <%= service.user.name %></span></li>
                            <li class="widget-49-meeting-item"><span>Dueño de la mascota: <%= service.pet.user.name %></span></li>
                            <% if service.state == 'completed' %>
                              <li class="widget-49-meeting-item"><span>Price: <%= service.price %></span></li>


                            <div class="form-floating">

                            <%= simple_form_for [@pet, service] do |f| %>
                              <div class="form-inputs">

                                <%= f.input :rating, label: 'Rating', required: true, class: "form-control" %>
                                <%= f.input :review, label: 'Review:', required: true %>
                                <%= f.hidden_field :state, value: "reviewed" %>
                              </div>

                              <div class="form-actions">
                                <%= f.button :submit, 'Send', class: "btn btn-primary" %>
                              </div>
                            <% end %>
                            </div>








                            <% end %>
                        </ol>
                        <div class="widget-49-meeting-action">

                          <div class="d-flex justify-content-between">
                          <% if service.state == 'denied' %>
                            <%= link_to 'Find pet-walker', edit_service_path(service), class: "btn btn-info"  %>
                            <%= button_to 'Discard', service_path(service), method: :delete, class: "btn btn-info"  %>
                          <% end %>
                          </div>







                          <% if service.state == 'started' %>
                            <%= button_to 'Start', service_path(service), method: :patch, params: { state: 'in process' }, class: "btn btn-info"  %>
                          <% end %>

                          <% if service.state == 'finished' %>
                            <%= button_to 'Finalize', service_path(service), method: :patch, params: { state: 'completed' }, class: "btn btn-info"  %>
                          <% end %>




                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

<% end %>

app/views/services/edit.html.erb
<h1 class="mt-5 text-center title">Editar servicio</h1>

<%= render 'form' %>

app/views/services/index.html.erb
<div class="row row-cols-3">
  <% @services.each do |service| %>



    <%= render 'service', service: service %>



  <% end %>
</div>


<%= link_to 'Back to home', root_path, class: 'btn btn-primary' %>

app/views/services/show.html.erb
<h1>This is the show view of service</h1>

<div class="row">
  <div class="card" style="width: 18rem;">
    <% if @service.pet.photo.attached? %>
      <%= cl_image_tag @service.pet.photo.key, class: "card-img-top" %>
    <% else %>
      <i class="fa-solid fa-paw card-img-top"></i>
    <% end %>

    <div class="card-body">
      <h4 class="card-title"><%= @service.schedule %></h4>
      <h6 class="card-subtitle">Petowner:</h6>
      <p class="card-text"><%= @service.pet.user.email %></p>
      <h6 class="card-subtitle">Petwalker:</h6>
      <p class="card-text"><%= @service.user.email %></p>
    </div>
  </div>
</div>


<%= link_to 'Back', services_path, class: 'btn btn-info' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="navbar-brand">
        <%= image_tag "icon.png" %>
        <%= link_to 'The walking pet', root_path, class: 'brand' %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My Services", services_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "profile.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to 'Editar usuario', edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to 'My pets', pets_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-primary" %>

          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container emp-profile">
  <div class="row">
    <div class="col-md-5">
      <div class="profile-img">
        <% if @petwalker.photo.attached? %>
          <%= cl_image_tag @petwalker.photo.key, class: 'card-img-top'%>
        <% else %>
          <%= image_tag "petwalker.png", size: "auto", style: "border-radius: 5%; width: 100%", class: "avatar card-img-top bd-placeholder-img"%>
        <% end %>
      </div>
    </div>
    <div class="col-md-7">
      <div class="profile-head">
        <h5 class="pb-2"><%= @petwalker.name %></h5>
        <%= @petwalker.description %>

        <ul class="nav nav-tabs">
          <li class="nav-item mt-5">Reviews</li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-md-5">
        <div class="profile-work">
          <p>Social Media</p>
          <i class="fa-brands fa-facebook"></i>
          <i class="fa-brands fa-square-instagram"></i>
          <<i class="fa-brands fa-twitter"></i>
        </div>
      </div>
      <div class="col-md-7">
        <div class="tab-content profile-tab">
          <div class="tab-pane fade show active">



     <% @reviews.each do |review| %>
        <%= review[:rating] %>⭐<%= review[:message] %>
      <% end %>


          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= simple_form_for [@pet, @service] do |f| %>
  <div class="form-inputs">
    <%= f.association :user, collection: @petwalkers, selected: 1, label: "Petwalker", label_method: :name %>
    <%= f.input :schedule, label: 'Schedule:', required: true %>
  </div>

  <% if user_signed_in? %>
    <div class="form-actions">
      <%= f.button :submit, 'Schedule', class: "mb-5 btn btn-sm btn-danger" %>
    </div>
  <% else %>
    <div class="form-actions">
      <%= link_to 'Schedule', new_user_session_path, class: 'mb-5 btn btn-sm btn-danger' %>
    </div>
  <% end %>
<% end %>